FROM golang:1.22.2 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /doc

# Run the tests in the container
FROM build-stage AS run-test-stage
RUN CGO_ENABLED=0 go test -v ./...

# Deploy the application binary into a image
#ToDo Decide distribution image
FROM distroimage AS build-release-stage

WORKDIR /

COPY --from=build-stage /doc /doc

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/docker-gs-ping"]